# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Koba's website
email: kobakhit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog where I write about data science, math, stats, web design and grad school.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kobakhit.com" # the base hostname & protocol for your site
twitter_username: kobakhit
github_username:  kobakhit

# Build settings
markdown: kramdown
# redcarpet:
#     extensions: ["with_toc_data"]
kramdown:
  input: GFM
  syntax_highlighter: rouge


# redcarpet:
#   extensions: ["fenced_code_blocks","no_intra_emphasis"]
exclude:
  - _posts/**/*.jpg
  - _posts/**/*.png
  - _posts/**/*.gif
  
gems:
 - jekyll-gist
 - jekyll-paginate
